project_id = "italk-local"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://nickzen108.github.io/iTalk/"
additional_redirect_urls = ["http://127.0.0.1:8080"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[auth.hook.before_user_created]
enabled = true
uri = "pg-functions://postgres/public/hook_allow_invited_staff"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
file_size_limit = "5MiB"
